setwd("C:/Users/hp/datasciencecoursera/Course4(Exploratory Analysis)/Week1")
data <- read.csv("F:/course/1/1.4/Week 1/household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?", stringsAsFactors = FALSE, dec = ".")
# str(data)
data <- data[data$Date == "1/2/2007" | data$Date == "2/2/2007",]
dateTime <- strptime(paste(data$Date, data$Time, sep = " "), "%d/%m/%Y %H:%M:%S")
globalactivepower <- as.numeric(data$Global_active_power)
globalreactivepower <- as.numeric(data$Global_reactive_power)
voltage <- as.numeric(data$Voltage)
submetering1 <- as.numeric(data$Sub_metering_1)
submetering2 <- as.numeric(data$Sub_metering_2)
submetering3 <- as.numeric(data$Sub_metering_3)
png("plot1.png", width=480, height=480)
hist(globalactivepower, col="red", main="Global Active Power", xlab="Global Active Power (kilowatts)")
dev.off()
png("plot2.png", width=480, height=480)
plot(dateTime, globalactivepower, type = "l", col = "black", xlab = "", ylab = "Global Active Power (kilowatts)", main = "")
dev.off()
png("plot3.png", width=480, height=480)
plot(dateTime, submetering1, type = "l", col = "black", xlab = "", ylab = "Energy sub metering", main = "")
lines(dateTime, submetering2, type = "l", col = "blue")
lines(dateTime, submetering3, type = "l", col = "red")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.off()
png("plot4.png", width=480, height=480)
par(mfrow = c(2,2))
plot(dateTime, globalactivepower, type = "l", col = "black", xlab = "", ylab = "Global Active Power (kilowatts)", main = "")
plot(dateTime, voltage, type = "l", col = "black", xlab = "datetime", ylab = "Voltage", main = "")
plot(dateTime, submetering1, type = "l", col = "black", xlab = "", ylab = "Energy sub metering", main = "")
lines(dateTime, submetering2, type = "l", col = "blue")
lines(dateTime, submetering3, type = "l", col = "red")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
plot(dateTime, globalreactivepower, type = "l", col = "black", xlab = "datetime", ylab = "Global_reactive_power", main = "")
dev.off()